name: Publish PPA
on:
  workflow_run:
    workflows: ["Bump version workflow"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  publish-ppa:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish PPA
        uses: atareao/publish-ppa-package-from-source@v1
        with:
          repository: "atareao/atareao"
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          deb_email: "atareao@atareao.es"
          deb_fullname: "Lorenzo Carbonell"
